version: '3'

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"  # Client port
      - "8222:8222"  # HTTP monitoring port
    command: "--addr 0.0.0.0 --cluster nats://0.0.0.0:6222 --http_port 8222"
    restart: unless-stopped